version: '3.9'

services:
  python-producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-producer
    ports:
      - 5051:5051
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - network1

networks:
  network1:
    name: pipeline_monitoring
    external: true
