version: '3.9'

services:
  statsd-exporter:
    image: prom/statsd-exporter:master
    container_name: airflow-statsd-exporter
    ports:
      - "9102:9102"
      - "9125:9125/udp"
    command:
      - '--statsd.listen-udp=:9125'
      - '--web.listen-address=:9102'
    networks:
      - network1

  prometheus:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'    
    networks:
      - network1




  # Define your data pipeline services here

volumes:
  prometheus_data:

networks:
  network1:
    name: pipeline_monitoring
    external: true