version: '3.9'

services:
  prometheus:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'

  # Define your data pipeline services here

volumes:
  prometheus_data:
