global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'airflow-statsd-exporter'
    static_configs:
      - targets: ['airflow-statsd-exporter:9102']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka_exporter:9308']