{
 "title": "Amazon CloudWatch Logs",
 "description": "Visualize Amazon CloudWatch Log based metrics",
 "tags": [
  "Amazon",
  "AWS",
  "CloudWatch",
  "Logs"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   { "name": "period", "label": "Period [sec]", "query": "60,300,3600" }
  ]
 },
 "panels": [
  {
   "title": "Incoming log events [count/sec]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Logs,LogGroupName} MetricName=\"IncomingLogEvents\"', 'Sum', $period))/$period",
     "metricEditorMode": 1,
     "metricName": "IncomingLogEvents",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Incoming bytes [bytes/sec]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Logs,LogGroupName} MetricName=\"IncomingBytes\"', 'Sum', $period))/$period",
     "metricEditorMode": 1,
     "metricName": "IncomingLogEvents",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
   "options": {
    "content": "For more information about the available metrics for Amazon CloudWatch Logs, please visit the [CloudWatch documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CloudWatch-Logs-Monitoring-CloudWatch-Metrics.html)."
   },
   "targets": [
    { "region": "default", "statistic": "Average" }
   ]
  },
  {
   "title": "Python producer logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expression": "fields @timestamp, @message |\n sort @timestamp desc |\n limit 20",
     "logGroups": [
      {
       "accountId": "145723653607",
       "arn": "arn:aws:logs:ap-southeast-2:145723653607:log-group:/ecs/python-producer:*",
       "name": "/ecs/python-producer"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Kafka logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expression": "fields @timestamp, @message |\n sort @timestamp desc |\n limit 20",
     "logGroups": [
      {
       "accountId": "145723653607",
       "arn": "arn:aws:logs:ap-southeast-2:145723653607:log-group:/ecs/kafka:*",
       "name": "/ecs/kafka"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Pyspark consumer logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expression": "fields @timestamp, @message |\n sort @timestamp desc |\n limit 20",
     "logGroups": [
      {
       "accountId": "145723653607",
       "arn": "arn:aws:logs:ap-southeast-2:145723653607:log-group:/ecs/pyspark-consumer:*",
       "name": "/ecs/pyspark-consumer"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Flask api logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expression": "fields @timestamp, @message |\n sort @timestamp desc |\n limit 20",
     "logGroups": [
      {
       "accountId": "145723653607",
       "arn": "arn:aws:logs:ap-southeast-2:145723653607:log-group:/ecs/flask-api:*",
       "name": "/ecs/flask-api"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Prometheus logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expression": "fields @timestamp, @message |\n sort @timestamp desc |\n limit 20",
     "logGroups": [
      {
       "accountId": "145723653607",
       "arn": "arn:aws:logs:ap-southeast-2:145723653607:log-group:/ecs/prometheus:*",
       "name": "/ecs/prometheus"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Grafana logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expression": "fields @timestamp, @message |\n sort @timestamp desc |\n limit 20",
     "logGroups": [
      {
       "accountId": "145723653607",
       "arn": "arn:aws:logs:ap-southeast-2:145723653607:log-group:/ecs/grafana:*",
       "name": "/ecs/grafana"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}