{
 "title": "Market Mind",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Market Sentiment Overview",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "market_mind",
     "rawSql": "SELECT \ncase \nwhen avg_score <= -0.35 then \"Bearish\"\nwhen avg_score > -0.35 and avg_score <= -0.15 then \"Somewhat-Bearish\"\nwhen avg_score > -0.15 and avg_score < 0.15 then \"Neutral\"\nwhen avg_score >= 0.15 and avg_score < 0.35 then \"Somewhat-Bullish\"\nwhen avg_score >= 0.35 then \"Bullish\" end as `Market Sentiment`,\navg_score as `Sentimnet Score`\nFROM market_mind.alpha_vantage_agg \norder by date_recorded desc\nlimit 1\n\n-- \"x <= -0.35: Bearish; \n-- -0.35 < x <= -0.15: Somewhat-Bearish;\n-- -0.15 < x < 0.15: Neutral; \n-- 0.15 <= x < 0.35: Somewhat_Bullish; \n-- x >= 0.35: Bullish\""
    },
    {
     "dataset": "market_mind",
     "sql": {
      "columns": [],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     },
     "table": "reddit_agg"
    }
   ]
  },
  {
   "title": "Market Emotion Overview",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select emotion_name, \nround(avg_score, 2)\nfrom reddit_agg\n-- where date_recorded = curdate()\nlimit 7\n"
    }
   ]
  },
  {
   "title": "Market Sentiment Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \ncase \nwhen avg_score <= -0.35 then \"Bearish\"\nwhen avg_score > -0.35 and avg_score <= -0.15 then \"Somewhat-Bearish\"\nwhen avg_score > -0.15 and avg_score < 0.15 then \"Neutral\"\nwhen avg_score >= 0.15 and avg_score < 0.35 then \"Somewhat-Bullish\"\nwhen avg_score >= 0.35 then \"Bullish\" end as `Market Sentiment`,\navg_score as `Sentimnet Score`,\ndate(date_recorded) as `date`\nFROM market_mind.alpha_vantage_agg \norder by date_recorded desc\n\n-- \"x <= -0.35: Bearish; \n-- -0.35 < x <= -0.15: Somewhat-Bearish;\n-- -0.15 < x < 0.15: Neutral; \n-- 0.15 <= x < 0.35: Somewhat_Bullish; \n-- x >= 0.35: Bullish\""
    }
   ]
  },
  {
   "title": "Market Emotion Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "\nSELECT \n    date_recorded,\n    MAX(CASE WHEN emotion_name = 'neutral' THEN avg_score ELSE NULL END) AS 'neutral',\n    MAX(CASE WHEN emotion_name = 'joy' THEN avg_score ELSE NULL END) AS 'joy',\n    MAX(CASE WHEN emotion_name = 'fear' THEN avg_score ELSE NULL END) AS 'fear',\n    MAX(CASE WHEN emotion_name = 'sadness' THEN avg_score ELSE NULL END) AS 'sadness',\n    MAX(CASE WHEN emotion_name = 'surprise' THEN avg_score ELSE NULL END) AS 'surprise',\n    MAX(CASE WHEN emotion_name = 'anger' THEN avg_score ELSE NULL END) AS 'anger',\n    MAX(CASE WHEN emotion_name = 'disgust' THEN avg_score ELSE NULL END) AS 'disgust'\nFROM\n    reddit_agg \nGROUP BY\n    date_recorded\nORDER BY\n    date_recorded;\n\n"
    }
   ]
  },
  { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 } }
 ]
}