{
 "title": "Grafana monitoring",
 "description": "Metrics about Grafana",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests by routing group",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(grafana_api_response_status_total[5m]))",
     "legendFormat": "api"
    },
    {
     "expr": "sum(irate(grafana_proxy_response_status_total[5m]))",
     "legendFormat": "proxy"
    },
    {
     "expr": "sum(irate(grafana_page_response_status_total[5m]))",
     "legendFormat": "web"
    }
   ]
  },
  {
   "title": "Grafana performance",
   "type": "timeseries",
   "description": "Aggregated over all Grafana nodes.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"grafana\"})",
     "legendFormat": "go routines",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=\"grafana\"})",
     "legendFormat": "memory usage"
    }
   ]
  },
  {
   "title": "Prometheus response size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(grafana_datasource_response_size_bytes_bucket[$__rate_interval])))"
    }
   ]
  }
 ]
}