{
 "title": "Metrics Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Python producer # messages per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(python_producer_produced_messages_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Kafka # of messages per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(kafka_consumergroup_current_offset_sum{topic=\"trades_streaming\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Pyspark consumer insert to DB time per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(pyspark_consumer_insert_time_seconds_sum[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Socket IO active connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "socket_io_active_connections" }
   ]
  },
  {
   "title": "Airflow running tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "airflow_executor_running_tasks" }
   ]
  },
  {
   "title": "Airflow task overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "airflow_ti_start", "legendFormat": "airflow_ti_start" },
    { "expr": "airflow_ti_finish", "legendFormat": "airflow_ti_finish" },
    { "expr": "airflow_ti_successes", "legendFormat": "airflow_ti_successes" }
   ]
  }
 ]
}