version: '3.9'


services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0.arm64
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: echo srvr | nc zookeeper 2181 || exit 1
      start_period: 10s
      retries: 20
      interval: 10s
    networks:
      - network1

  broker:
    image: confluentinc/cp-kafka:7.5.0.arm64
    hostname: broker
    container_name: broker
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - '29092:29092'
      - '9092:9092'
      - '9091:9091'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: broker
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_JMX_PORT: '9091'
      KAFKA_JMX_HOSTNAME: localhost
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - network1

  kafka_exporter:
    image: bitnami/kafka-exporter:1.7.0
    container_name: kafka_exporter
    depends_on:
      broker:
        condition: service_healthy
    ports:
      - '9308:9308'
    environment:
      KAFKA_SERVER: broker:9092
    command:
      - '--kafka.server=broker:9092'
      - '--kafka.version=3.5.0'
    networks:
      - network1

networks:
  network1:
    name: pipeline_monitoring
    external: true