version: '3.9'

services:
  pyspark-consumer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - network1

networks:
  network1:
    name: streaming_network
    external: true
