version: '3.9'

services:
  api:
    build: .
    container_name: flask-api
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - network1

networks:
  network1:
    name: pipeline_monitoring
    external: true