import React from "react";
import { Cell, XAxis, YAxis, Tooltip, BarChart, Bar } from "recharts";

function getBarColor(value) {
  /**
   * Returns a color for the bar based on the value.
   * This function is mainly used to set the color and the according opacity of the bar.
   */
  const opacity = Math.min(1, value * 5);
  return `rgba(91,192,235, ${opacity})`;
}

const RedditBarChart = ({ data, title }) => {
  /**
   * This const as a function component that renders a bar chart.
   * @Param {Array} data - An array of reddit data.
   * @Param {String} title - The title of the bar chart.
   * @Return {Component} - A bar chart component consisting of a title and a bar chart with html styling.
   */

  // entries() method turns an object into an array of [key, value] pairs.
  const dataArray = Object.entries(data)
    // map each entry to an object with emotion and value.
    // eg. { emotion: "anger", value: 0.1 }
    .map(([key, value]) => ({ emotion: key, value }))
    // filter out the dateRecorded entry.
    .filter((entry) => entry.emotion !== "dateRecorded")
    /**
     * sort the array by value in descending order.
     * sort((a, b)) => [b.value - a.value])
     * if b.value - a.value > 0, b.value is larger than a.value, so b will be put before a.
     */
    .sort((a, b) => b.value - a.value);

  return (
    <div style={{ textAlign: "center" }}>
      <h3>{title}</h3>
      <BarChart
        width={500}
        height={300}
        data={dataArray}
        margin={{ top: 5, right: 10, left: 10, bottom: 40 }}
      >
        <XAxis dataKey="emotion" tick={{ angle: -45, textAnchor: "end" }} />
        <YAxis
          tick={{ fontSize: 12 }}
          label={{ value: "Score", angle: -90, position: "insideLeft" }}
        />
        <Tooltip />
        <Bar dataKey="value">
          {/* map each bar to a cell with a color, index is being autogenerated by map function */}
          {dataArray.map((entry, index) => (
            <Cell key={`cell-${index}`} fill={getBarColor(entry.value)} />
          ))}
        </Bar>
      </BarChart>
    </div>
  );
};

export default RedditBarChart;
